# Generated by Django 4.0 on 2022-01-28 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 1, 28, 20, 1, 34, 776249), max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foro',
            name='fecha',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 1, 28, 20, 1, 34, 776249), max_length=100, null=True),
        ),
    ]
